import streamlit as st
import requests
import json

API_URL = "http://localhost:8000/v1/evaluate"

st.set_page_config(layout="wide", page_title="Consistency Check")

st.title("Generative Output Consistency Evaluator")
st.markdown("Validate LLM responses against source context using NLI, semantic overlap, and lexical checks.")

col1, col2 = st.columns(2)

with col1:
    st.subheader("Source Context")
    ctx_input = st.text_area("System prompt, RAG chunks, or factual baseline", height=300)

with col2:
    st.subheader("Generated Output")
    gen_input = st.text_area("The text generated by the AI model", height=300)

if st.button("Run Analysis", type="primary"):
    if not ctx_input or not gen_input:
        st.warning("Ensure both fields are populated.")
    else:
        with st.spinner("Analyzing semantic structures and entailment..."):
            try:
                resp = requests.post(API_URL, json={
                    "source_context": ctx_input,
                    "generated_text": gen_input
                })
                
                if resp.status_code == 200:
                    payload = resp.json().get("data", {})
                    
                    st.divider()
                    st.subheader("Results")
                    
                    r1, r2, r3 = st.columns(3)
                    
                    nli = payload.get("nli_inference", {})
                    r1.metric("Primary NLI Verdict", nli.get("dominant_label", "N/A"))
                    r1.caption(f"Entailment Prob: {nli.get('entailment_prob', 0):.2f}")
                    
                    alignment = payload.get("factual_alignment", {})
                    r2.metric("Entity Overlap", f"{alignment.get('entity_overlap', 0) * 100:.1f}%")
                    r2.caption(f"Token Overlap: {alignment.get('token_overlap', 0) * 100:.1f}%")
                    
                    structural = payload.get("structural_metrics", {})
                    r3.metric("Gibberish Index", structural.get("gibberish_ratio", 0))
                    r3.caption(f"Coherence: {structural.get('coherence_score', 0):.2f}")
                    
                    with st.expander("View Raw JSON Dump"):
                        st.json(payload)
                else:
                    st.error(f"API Error: {resp.text}")
            except Exception as e:
                st.error(f"Connection failed: {str(e)}")
